### ISSUE TITLE
/login gives 404 Not Found

### ISSUE THREAD

**Issue by Emmely2008** [HackerNews-lsd2017/hacker-news#10] opened 2017-11-08 11:15 UTC
The url http://fe-hacker-news.s3-website-eu-west-1.amazonaws.com/login gives 404.

**To replicate:**

1. Go to http://fe-hacker-news.s3-website-eu-west-1.amazonaws.com
2. Click on login in the main menu - the login pages displays.
3. Do a refresh of the page in the web browser (press F5)
4. The page displays an error message: 

404 Not Found

Code: NoSuchKey
Message: The specified key does not exist.
Key: login
RequestId: 3CEE5B420E61F804
HostId: CrOxgI7aVgSUBdqItu6Op0jX+3wn1hLUqavEinBiE0mABQzo5zQFWzErqtc77/QhJ9HPm1uJJr0=

**Comment by Ldaxar** [comment] 2017-11-11 17:41
Hey @Emmely2008  

I was able to replicate your issue. I have assigned our fronted experts that will take a look at it and try to resolve this issue as soon as possible.   

Thank you for your input!

**Comment by WillVill** [comment] 2017-11-12 18:31
This will be fixed fairly soon. We will add CloudFront to look over our S3 bucket which will take care of this issue, which is caused by client-side rendering.

**Comment by WillVill** [comment] 2017-11-15 12:15
This has been fixed. Our website now has a new url. Please use: http://d3com7bor8tlib.cloudfront.net/

**Closed as completed** 2017-11-15 12:15 UTC
